# Generated by Django 3.2.9 on 2021-11-17 11:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_postmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 11, 46, 19, 814421, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmodel',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(default=datetime.datetime(2021, 11, 17, 11, 46, 23, 795897, tzinfo=utc), upload_to='media/post/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmodel',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 11, 46, 28, 530043, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmodel',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2021, 11, 17, 11, 46, 32, 716277, tzinfo=utc), editable=False, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
