# Generated by Django 3.1.5 on 2021-08-24 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_iletisimmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iletisimmodel',
            old_name='isim_soysim',
            new_name='isim_soyad',
        ),
    ]
