# Generated by Django 3.1.5 on 2021-08-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210824_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iletisimmodel',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='iletisimmodel',
            name='isim_soyad',
            field=models.CharField(max_length=100, verbose_name='İsim Soyad'),
        ),
    ]
