# Generated by Django 3.1.5 on 2021-09-24 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210824_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yorummodel',
            old_name='guncelleme_tarihi',
            new_name='duzenleme_tarihi',
        ),
    ]
