# Generated by Django 3.1.5 on 2021-10-16 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_auto_20211016_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yorummodel',
            name='yazan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorum', to='account.customusermodel'),
        ),
    ]
