# Generated by Django 3.1.5 on 2021-10-21 19:03

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20211016_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategorimodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='isim', unique=True),
        ),
        migrations.AlterField(
            model_name='yazilarmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='baslik', unique=True),
        ),
    ]
