#from .iletisim import iletisim
#from .yaziEkle import yaziEkle
#from .yaziGuncelle import yaziGuncelle
from .anasayfa import anasayfa
from .iletisim import IletisimFormView
from .kategori import KategoriListView
from .yazilarim import yazilarim
from .detay import DetayView
from .yaziEkle import YaziEkleCreateView
from .yaziGuncelle import YaziGuncelleUpdateView
from .yaziSil import YaziSilDeleteView
from .yorumSil import yorumSil